image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

build:
  stage: build
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - mkdir Rivet
    - find -maxdepth 1 -mindepth 1 -not -name Rivet -exec mv {} Rivet/ \;
    - SCRAM_ARCH=slc6_amd64_gcc630 /cvmfs/cms.cern.ch/common/scramv1 project CMSSW CMSSW_10_0_0
    - mv Rivet CMSSW_10_0_0/src/
    - cd CMSSW_10_0_0/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - /cvmfs/cms.cern.ch/common/scram b -j 8
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_10_0_0

list-analyses:
  stage: test
  tags:
    - docker
    - cvmfs
  script:
    - cd CMSSW_10_0_0/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - mkdir -p GeneratorInterface/RivetInterface/test/
    - wget https://raw.githubusercontent.com/cms-sw/cmssw/CMSSW_10_0_X/GeneratorInterface/RivetInterface/test/rivetSetup.sh -P GeneratorInterface/RivetInterface/test/
    - source Rivet/rivetSetup.sh
    - rivet --list-analyses

check-tabs:
  stage: test
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - cd CMSSW_10_0_0/src/Rivet
    - ls -l
    - echo '! grep -rnP "\t" * | grep "\.cc"' | bash
