image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

build:
  stage: build
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - SCRAM_ARCH=slc6_amd64_gcc530 /cvmfs/cms.cern.ch/common/scramv1 project CMSSW CMSSW_8_1_0
    - mkdir -p CMSSW_8_1_0/src/Rivet
    - cp -r !(CMSSW_8_1_0) CMSSW_8_1_0/src/Rivet/
    - cd CMSSW_8_1_0/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - /cvmfs/cms.cern.ch/common/scram b -j 8
