image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

merge:
  stage: build
  script:
    - git merge origin/master --no-commit --no-ff

build:
  stage: build
  tags:
    - docker
    - cvmfs
  before_script:
    - git merge origin/master --no-commit --no-ff
  script:
    - pwd
    - ls -l
    - SCRAM_ARCH=slc6_amd64_gcc530 /cvmfs/cms.cern.ch/common/scramv1 project CMSSW CMSSW_8_1_0
    - cd CMSSW_8_1_0/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - mkdir -p TopMonteCarlo/RivetTop
    - cp ../../BuildFile.xml TopMonteCarlo/RivetTop/
    - cp -r ../../data TopMonteCarlo/RivetTop/
    - cp -r ../../interface TopMonteCarlo/RivetTop/
    - cp -r ../../src TopMonteCarlo/RivetTop/
    - cp -r ../../test TopMonteCarlo/RivetTop/
    - mkdir -p GeneratorInterface/RivetInterface
    - ln -s $CMSSW_BASE/src/TopMonteCarlo/RivetTop/data $CMSSW_BASE/src/GeneratorInterface/RivetInterface/
    - cd TopMonteCarlo/RivetTop
    - /cvmfs/cms.cern.ch/common/scram b -j 8
    - cd test
    - cmsRun runRivetAnalyzer_8TeV_cfg.py maxEvents=1000
    - cmsRun runRivetAnalyzer_13TeV_cfg.py maxEvents=1000